#
# Set up for a Harry Potter server.
#
# Crafting is not allowed, it is assumed each player has one wand
# they will keep throughout their play experience.
#

# Give the player a Ticket from Ollivander to start their journey
# This can be exchanged for a Wand Box from an NPC by doing the following:
# /npc create Ollivander
# /trait magic
# /mtrait spell ollivander
welcome_wand: ticket

default_wand: potterwand

# Start players off with some Spell Points
sp_default: 100

# This is a modifier on the default survival configs
inherit: survival

# Turn off the survival spells, but allow them to be inherited from
disable_inherited:
 - spells

skip_inherited:
 - wands
 - paths
 - crafting
 - classes
 - mobs

# Don't allow crafting
enable_crafting: false

# Custom physical economy
currency:
  emerald:
    worth: 1
    name: Galleon
    name_plural: Galleons

# Use the potter RP
resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-potter-RP-8-1.16.zip"

# Default class
default_mage_class: wizard

# Set up some custom currency
custom_currency:
 tc:
  max: 9999
  default: 0
  icon: skull:http://textures.minecraft.net/texture/b11206551e723c356c23b32383abd19e6d7e9e5988f191e7866ae89ed6cb24
 ac:
  max: 9999
  default: 0
  icon: skull:http://textures.minecraft.net/texture/82d8ccac4d982bf3199761c1c74b9aa18e312ff5ca0a6e51b77a87abad610b

alternate_resource_packs:
  potter:
    url: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-potter-RP-8-1.16.zip"
