# Loads in base potter configs
example: potter

# Gives the correct wand when the player does /wand
default_wand: playerwand

# Gives the correct item at the beginning of the player's journey
welcome_wand: ticket

# Enables custom crafting recipes
enable_crafting: true
