# Disables the SP system in favor of AC
sp_enabled: false

# Defines custom currencies
custom_currency:
  galleon:
    max: 9999
    default: 0
    icon: gold_nugget
  ac:
    max: 9999
    default: 0
    icon: iron_axe{CustomModelData:5}
  cc:
    max: 9999
    default: 0
    icon: iron_axe{CustomModelData:6}
  mobxp:
    max: 99999
    default: 0
    icon: iron_axe{CustomModelData:12}
