base_wand:
  # When the drop key is pressed while holding the wand, open the spell
  # inventory
  drop: toggle
  # When left clicking while holding the wand, cast the active spell
  left_click: cast
  # When right clicking while holding the wand, open the spell inventory
  right_click: toggle
  # When the swap key is pressed while holding the wand, cycle between the
  # multiple spell hotbars
  swap: cycle_hotbar
  # Leave wand messages on
  quiet: 0

potterwand:
  enabled: false

randomizedpotterwand:
  enabled: false

wandbox:
  inherit: false
  icon: wooden_hoe{CustomModelData:100}
  undroppable: true
  lore:
    - "$description"
  replacement: playerwand
  right_click: replace
  effects:
    replace:
      - sound: potterplus.whoosh_loud
      - class: EffectRepeat
        delay: 500
        location: origin
        firework: burst
        color: FFFFFF
        color2: random

playerwand:
  inherit: base_wand
  icon: wooden_hoe{CustomModelData:1},wooden_hoe{CustomModelData:2},wooden_hoe{CustomModelData:3},wooden_hoe{CustomModelData:4},wooden_hoe{CustomModelData:5}
  randomize_icon: diamond_hoe{CustomModelData:138}
  display_name: "&d$name &8> &6$spell"
  hotbar_count: 2
  quiet: 0
  active_spell: lumos
  spells:
    - lumos
  classes:
    - wizard
  effects:
    randomize:
      - sound: potterplus.swish
        source_location: feet
        effectlib:
          class: AnimatedBall
          particle: fireworks_spark
          particle_data: 0.1
          duration: 5000
