sounddemo:
  icon: note_block
  category: staff
  hidden: true
  actions:
    cast:
      - class: Selector
  effects:
    magicbonk:
      - sound: magic.bonk
    magicsonic:
      - sound: magic.sonic
    magiccrack:
      - sound: magic.crack
    magicelectrify:
      - sound: magic.electrify
    magichit:
      - sound: magic.hit
    magicshimmercrack:
      - sound: magic.shimmer_crack
    magicshimmer:
      - sound: magic.shimmer
    magiczapcrack:
      - sound: magic.zap_crack
    magiczap:
      - sound: magic.zap
    magiczapbig:
      - sound: magic.zap_big
    magicteleport:
      - sound: magic.teleport
    magicshield:
      - sound: magic.shield
    magicburn:
      - sound: magic.burn
    magicignite:
      - sound: magic.ignite
    magicshimmerquiet:
      - sound: magic.shimmer_quiet
    magicflying:
      - sound: magic.flying
    magicshimmerbig:
      - sound: magic.shimmer_big
    magicshieldboom:
      - sound: magic.shield_boom
    magiczapup:
      - sound: magic.zap_up
    magicvanish:
      - sound: magic.vanish
    magicringing:
      - sound: magic.ringing
    magicpaperturn:
      - sound: magic.paperturn
    magicwandup:
      - sound: magic.wandup
    magicwanddown:
      - sound: magic.wanddown

    ppblock:
      - sound: potterplus.block
    ppcastblast:
      - sound: potterplus.cast_blast
    ppcastbreak:
      - sound: potterplus.cast_break
    ppcastfire:
      - sound: potterplus.cast_fire
    ppcastfireunique:
      - sound: potterplus.cast_fire_unique
    ppcastquiet:
      - sound: potterplus.cast_quiet
    ppcastsharp:
      - sound: potterplus.cast_sharp
    ppcastsharpalt:
      - sound: potterplus.cast_sharp_alt
    ppglass:
      - sound: potterplus.glass
    ppimpact:
      - sound: potterplus.impact
    pppotionbrew:
      - sound: potterplus.potion_brew
    ppquickcast:
      - sound: potterplus.quick_cast
    ppteleport:
      - sound: potterplus.teleport
    ppwhip:
      - sound: potterplus.whip
    ppwhooshloud:
      - sound: potterplus.whoosh_loud
    ppzap:
      - sound: potterplus.zap
    ppdarkwhoosh:
      - sound: potterplus.dark_whoosh
    ppevilwhoosh:
      - sound: potterplus.evil_whoosh
    ppignite:
      - sound: potterplus.ignite
    ppwhoosh:
      - sound: potterplus.whoosh
    ppswish:
      - sound: potterplus.swish
  parameters:
    options:
      - icon: paper
        name: "&9Sound Demo Info"
        lore:
          - "&8> &7Click a sound to demo it"
          - "&8> &dMagic &7sounds are marked purple"
          - "&8> &aPotterPlus &7sounds are marked green"
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.bonk"
        lore:
          - "&8> &7Click to play"
        effects: magicbonk
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.sonic"
        lore:
          - "&8> &7Click to play"
        effects: magicsonic
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.crack"
        lore:
          - "&8> &7Click to play"
        effects: magiccrack
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.electrify"
        lore:
          - "&8> &7Click to play"
        effects: magicelectrify
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.hit"
        lore:
          - "&8> &7Click to play"
        effects: magichit
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.shimmer_crack"
        lore:
          - "&8> &7Click to play"
        effects: magicshimmercrack
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.shimmer"
        lore:
          - "&8> &7Click to play"
        effects: magicshimmer
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.zap_crack"
        lore:
          - "&8> &7Click to play"
        effects: magiczapcrack
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.zap"
        lore:
          - "&8> &7Click to play"
        effects: magiczap
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.zap_big"
        lore:
          - "&8> &7Click to play"
        effects: magiczapbig
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.teleport"
        lore:
          - "&8> &7Click to play"
        effects: magicteleport
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.shield"
        lore:
          - "&8> &7Click to play"
        effects: magicshield
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.burn"
        lore:
          - "&8> &7Click to play"
        effects: magicburn
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.ignite"
        lore:
          - "&8> &7Click to play"
        effects: magicignite
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.shimmer_quiet"
        lore:
          - "&8> &7Click to play"
        effects: magicshimmerquiet
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.flying"
        lore:
          - "&8> &7Click to play"
        effects: magicflying
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.flying"
        lore:
          - "&8> &7Click to play"
        effects: magicflying
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.paperturn"
        lore:
          - "&8> &7Click to play"
        effects: magicpaperturn
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.wandup"
        lore:
          - "&8> &7Click to play"
        effects: magicwandup
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.wanddown"
        lore:
          - "&8> &7Click to play"
        effects: magicwanddown
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.shimmer_big"
        lore:
          - "&8> &7Click to play"
        effects: magicshimmerbig
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.shield_boom"
        lore:
          - "&8> &7Click to play"
        effects: magicshieldboom
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.zap_up"
        lore:
          - "&8> &7Click to play"
        effects: magiczapup
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.vanish"
        lore:
          - "&8> &7Click to play"
        effects: magicvanish
      - icon: purple_stained_glass
        name: "&7Sound&8: &6magic.ringing"
        lore:
          - "&8> &7Click to play"
        effects: magicringing

      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.block"
        lore:
          - "&8> &7Click to play"
        effects: ppblock
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_blast"
        lore:
          - "&8> &7Click to play"
        effects: ppcastblast
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_break"
        lore:
          - "&8> &7Click to play"
        effects: ppcastbreak
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_fire"
        lore:
          - "&8> &7Click to play"
        effects: ppcastfire
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_fire_unique"
        lore:
          - "&8> &7Click to play"
        effects: ppcastfireunique
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_quiet"
        lore:
          - "&8> &7Click to play"
        effects: ppcastquiet
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_sharp"
        lore:
          - "&8> &7Click to play"
        effects: ppcastsharp
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.cast_sharp_alt"
        lore:
          - "&8> &7Click to play"
        effects: ppcastsharpalt
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.glass"
        lore:
          - "&8> &7Click to play"
        effects: ppglass
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.impact"
        lore:
          - "&8> &7Click to play"
        effects: ppimpact
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.potion_brew"
        lore:
          - "&8> &7Click to play"
        effects: pppotionbrew
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.quick_cast"
        lore:
          - "&8> &7Click to play"
        effects: ppquickcast
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.teleport"
        lore:
          - "&8> &7Click to play"
        effects: ppteleport
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.whip"
        lore:
          - "&8> &7Click to play"
        effects: ppwhip
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.whoosh_loud"
        lore:
          - "&8> &7Click to play"
        effects: ppwhooshloud
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.zap"
        lore:
          - "&8> &7Click to play"
        effects: ppzap
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.dark_whoosh"
        lore:
          - "&8> &7Click to play"
        effects: ppdarkwhoosh
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.evil_whoosh"
        lore:
          - "&8> &7Click to play"
        effects: ppevilwhoosh
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.ignite"
        lore:
          - "&8> &7Click to play"
        effects: ppignite
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.whoosh"
        lore:
          - "&8> &7Click to play"
        effects: ppwhoosh
      - icon: green_stained_glass
        name: "&7Sound&8: &6potterplus.swish"
        lore:
          - "&8> &7Click to play"
        effects: ppswish

fxdemo:
  inherit: false
  icon: note_block
  category: staff
  hidden: true
  actions:
    cast:
      - class: Selector
  effects:
    animatedball:
      - location: target
        effectlib:
          class: AnimatedBall
          duration: $effect_duration
    arc:
      - location: target
        effectlib:
          class: Arc
          duration: $effect_duration
    atom:
      - location: target
        effectlib:
          class: Atom
          duration: $effect_duration
    bigbang:
      - location: target
        effectlib:
          class: BigBang
          duration: $effect_duration
    circle:
      - location: target
        effectlib:
          class: Circle
          duration: $effect_duration
    cloud:
      - location: target
        effectlib:
          class: Cloud
          duration: $effect_duration
    cone:
      - location: target
        effectlib:
          class: Cone
          duration: $effect_duration
    cube:
      - location: target
        effectlib:
          class: Cube
          duration: $effect_duration
    cylinder:
      - location: target
        effectlib:
          class: Cylinder
          duration: $effect_duration
    discoball:
      - location: target
        effectlib:
          class: DiscoBall
          duration: $effect_duration
    dna:
      - location: target
        effectlib:
          class: Dna
          duration: $effect_duration
    donut:
      - location: target
        effectlib:
          class: Donut
          duration: $effect_duration
    dragon:
      - location: target
        effectlib:
          class: Dragon
          duration: $effect_duration
    earth:
      - location: target
        effectlib:
          class: Earth
          duration: $effect_duration
    flame:
      - location: target
        effectlib:
          class: Flame
          duration: $effect_duration
    fountain:
      - location: target
        effectlib:
          class: Fountain
          duration: $effect_duration
    grid:
      - location: target
        effectlib:
          class: Grid
          duration: $effect_duration
          type: repeating
    heart:
      - location: target
        effectlib:
          class: Heart
          duration: $effect_duration
          type: repeating
    helix:
      - location: target
        effectlib:
          class: Helix
          duration: $effect_duration
    hill:
      - location: target
        effectlib:
          class: Hill
          duration: $effect_duration
    line:
      - location: target
        effectlib:
          class: Line
          duration: $effect_duration
    love:
      - location: target
        effectlib:
          class: Love
          duration: $effect_duration
    music:
      - location: target
        effectlib:
          class: Music
          duration: $effect_duration
    shield:
      - location: target
        effectlib:
          class: Shield
          duration: $effect_duration
    smoke:
      - location: target
        effectlib:
          class: Smoke
          duration: $effect_duration
    sphere:
      - location: target
        effectlib:
          class: Sphere
          duration: $effect_duration
    star:
      - location: target
        effectlib:
          class: Star
          duration: $effect_duration
    text:
      - location: target
        effectlib:
          class: Text
          duration: $effect_duration
          text: Magic!
    tornado:
      - location: target
        effectlib:
          class: Tornado
          duration: $effect_duration
    trace:
      - location: both
        effectlib:
          class: Trace
          duration: $effect_duration
    vortex:
      - location: target
        effectlib:
          class: Vortex
          duration: $effect_duration
    warp:
      - location: target
        effectlib:
          class: Warp
          duration: $effect_duration
    wave:
      - location: target
        effectlib:
          class: Wave
          duration: $effect_duration
  parameters:
    target: block
    target_self: true
    oty: 6
    range: 16
    effect_duration: 5000
    options:
      - icon: note_block
        name: "&7Effect&8: &6AnimatedBall"
        lore:
          - "&8> &7Click to play"
        effects: animatedball
      - icon: note_block
        name: "&7Effect&8: &6Arc"
        lore:
          - "&8> &7Click to play"
        effects: arc
      - icon: note_block
        name: "&7Effect&8: &6Atom"
        lore:
          - "&8> &7Click to play"
        effects: atom
      - icon: note_block
        name: "&7Effect&8: &6BigBang"
        lore:
          - "&8> &7Click to play"
        effects: bigbang
      - icon: note_block
        name: "&7Effect&8: &6Circle"
        lore:
          - "&8> &7Click to play"
        effects: circle
      - icon: note_block
        name: "&7Effect&8: &6Cloud"
        lore:
          - "&8> &7Click to play"
        effects: cloud
      - icon: note_block
        name: "&7Effect&8: &6Cone"
        lore:
          - "&8> &7Click to play"
        effects: cone
      - icon: note_block
        name: "&7Effect&8: &6Cube"
        lore:
          - "&8> &7Click to play"
        effects: cube
      - icon: note_block
        name: "&7Effect&8: &6Cylinder"
        lore:
          - "&8> &7Click to play"
        effects: cylinder
      - icon: note_block
        name: "&7Effect&8: &6DiscoBall"
        lore:
          - "&8> &7Click to play"
        effects: discoball
      - icon: note_block
        name: "&7Effect&8: &6Dna"
        lore:
          - "&8> &7Click to play"
        effects: dna
      - icon: note_block
        name: "&7Effect&8: &6Donut"
        lore:
          - "&8> &7Click to play"
        effects: donut
      - icon: note_block
        name: "&7Effect&8: &6Dragon"
        lore:
          - "&8> &7Click to play"
        effects: dragon
      - icon: note_block
        name: "&7Effect&8: &6Earth"
        lore:
          - "&8> &7Click to play"
        effects: earth
      - icon: note_block
        name: "&7Effect&8: &6Flame"
        lore:
          - "&8> &7Click to play"
        effects: flame
      - icon: note_block
        name: "&7Effect&8: &6Fountain"
        lore:
          - "&8> &7Click to play"
        effects: fountain
      - icon: note_block
        name: "&7Effect&8: &6Grid"
        lore:
          - "&8> &7Click to play"
        effects: grid
      - icon: note_block
        name: "&7Effect&8: &6Heart"
        lore:
          - "&8> &7Click to play"
        effects: heart
      - icon: note_block
        name: "&7Effect&8: &6Helix"
        lore:
          - "&8> &7Click to play"
        effects: helix
      - icon: note_block
        name: "&7Effect&8: &6Hill"
        lore:
          - "&8> &7Click to play"
        effects: hill
      - icon: note_block
        name: "&7Effect&8: &6Line"
        lore:
          - "&8> &7Click to play"
        effects: line
      - icon: note_block
        name: "&7Effect&8: &6Love"
        lore:
          - "&8> &7Click to play"
        effects: love
      - icon: note_block
        name: "&7Effect&8: &6Music"
        lore:
          - "&8> &7Click to play"
        effects: music
      - icon: note_block
        name: "&7Effect&8: &6Shield"
        lore:
          - "&8> &7Click to play"
        effects: shield
      - icon: note_block
        name: "&7Effect&8: &6Smoke"
        lore:
          - "&8> &7Click to play"
        effects: smoke
      - icon: note_block
        name: "&7Effect&8: &6Sphere"
        lore:
          - "&8> &7Click to play"
        effects: sphere
      - icon: note_block
        name: "&7Effect&8: &6Star"
        lore:
          - "&8> &7Click to play"
        effects: star
      - icon: note_block
        name: "&7Effect&8: &6Text"
        lore:
          - "&8> &7Click to play"
        effects: text
      - icon: note_block
        name: "&7Effect&8: &6Tornado"
        lore:
          - "&8> &7Click to play"
        effects: tornado
      - icon: note_block
        name: "&7Effect&8: &6Trace"
        lore:
          - "&8> &7Click to play"
        effects: trace
      - icon: note_block
        name: "&7Effect&8: &6Vortex"
        lore:
          - "&8> &7Click to play"
        effects: vortex
      - icon: note_block
        name: "&7Effect&8: &6Warp"
        lore:
          - "&8> &7Click to play"
        effects: warp
      - icon: note_block
        name: "&7Effect&8: &6Wave"
        lore:
          - "&8> &7Click to play"
        effects: wave
