spells:
  default:
    backfire: >-
      a:&cYour spell backfired on you!
    cast_play_message: >-
      a:&6$player &7cast &6$spell &7on you&8!
    fail: >-
      a:&cSpell failed!
    fizzle: >-
      a:&cYour spell fizzled!
    insufficient_resources: >-
      a:&cYou don't have enough &4$cost
    cooldown: >-
      a:&cYou must wait &4$time
    cancelled: >-
      a:&cYour spell was cancelled!
